name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update README with WakaTime
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.3.0
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: "chore: update development metrics"
          SHOW_TITLE: true
          TIME_RANGE: last_7_days
          SHOW_TOTAL: true
          LANG_COUNT: 6
